### ISSUE TITLE
check if the provided study accession is included in the list of study ids 

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/prs#13]
Now it's not obvious, but we only offer a certain set of study accession ids.

We need 1 check, to be able to fail early with an informative error message:
- check if the provided study accession is included in the list of study ids we have in our resource fail.
- if not inform the user that either the study accession id is invalid or it is not supported because it doesn't have harmonised summary stats.

Next week we need to implement 2 different checks to avoid being ambiguous. Adding as an issue.

_Originally posted by @cgpu in https://github.com/lifebit-ai/prs/pull/12#r502252054_

**Comment by mmeier93** [comment]
Addressed in sprint #115

```
if (params.gwas_cat_study_id){
  gwas_catalogue_ftp_ch = Channel
      .fromPath(params.gwas_catalogue_ftp, checkIfExists: true)
      .ifEmpty { exit 1, "GWAS catalogue ftp locations not found: ${params.gwas_catalogue_ftp}" }
      .splitCsv(header: true)
      .map { row -> tuple(row.study_accession, row.ftp_link_harmonised_summary_stats) }
      .filter{ it[0] == params.gwas_cat_study_id}
      .ifEmpty { exit 1, "The GWAS study accession number you provided does not come as a harmonized dataset that can be used as a base cohort "}
      .flatten()
      .last()
}
```
