### ISSUE TITLE
Task for @cgpu, upload to s3.

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/prs#8]
Task for @cgpu, upload to s3.

_Originally posted by @cgpu in https://github.com/lifebit-ai/prs/pull/7#discussion_r501796317_

**Comment by mmeier93** [comment]
Files to upload:
1) pheno_metadata = "https://raw.githubusercontent.com/lifebit-ai/prs/add-additional-plots/assets/metadata_phenotypes_mapping_file.csv"

2) gwas_catalogue_ftp = "https://raw.githubusercontent.com/lifebit-ai/prs/enable-usage-gwas-catalogue-stats/assets/ftp_locations_harmonized.csv" (I think this is one already done)

**Comment by mmeier93** [comment]
Corrected during Sprint #115 PR.
